from __future__ import annotations

import base64
import shutil
import struct
import zlib

import pytest

from floppyoctotouch_agent import thumbnails
from floppyoctotouch_agent.thumbnails import (
    ThumbnailScanner,
    decode_qoi,
    encode_png,
    extract_from_file,
)

from .conftest import SAMPLES, STORAGE

needs_samples = pytest.mark.skipif(not SAMPLES.is_dir(), reason="dev/sample-gcode not mounted")


def png_size(data: bytes) -> tuple[int, int]:
    assert data.startswith(thumbnails.PNG_MAGIC)
    return struct.unpack(">II", data[16:24])


def png_pixels(data: bytes) -> bytes:
    """Raw scanlines (filter byte + RGBA) of a PNG written by encode_png."""
    idat = data.index(b"IDAT")
    length = struct.unpack(">I", data[idat - 4 : idat])[0]
    return zlib.decompress(data[idat + 4 : idat + 4 + length])


def block(tag: str, width: int, height: int, data: bytes) -> str:
    b64 = base64.b64encode(data).decode()
    lines = [f"; {tag} begin {width}x{height} {len(b64)}"]
    lines += [f"; {b64[i : i + 78]}" for i in range(0, len(b64), 78)]
    return "\n".join([*lines, f"; {tag} end", ""])


def tiny_png(width: int, height: int) -> bytes:
    return encode_png(width, height, bytes([10, 20, 30, 255]) * width * height)


@needs_samples
@pytest.mark.parametrize(
    ("name", "size"),
    [
        ("calibration-cube_prusaslicer.gcode", (220, 124)),
        ("coaster_prusaslicer-qoi.gcode", (220, 124)),
        ("tatara-logo_orcaslicer.gcode", (300, 300)),
        ("3dbenchy_prusaslicer.gcode", (300, 300)),
    ],
)
def test_samples_give_their_largest_thumbnail_as_png(name, size):
    thumb = extract_from_file(SAMPLES / name)
    assert thumb is not None
    assert thumb.mime == "image/png"
    assert png_size(thumb.data) == size


@needs_samples
def test_qoi_is_decoded_pixel_perfect():
    thumb = extract_from_file(SAMPLES / "coaster_prusaslicer-qoi.gcode")
    rows = png_pixels(thumb.data)
    assert len(rows) == 124 * (1 + 220 * 4)
    # The generator draws a teal disc on a dark background (dev/tools/make_sample_gcode.py).
    corner = rows[1:5]
    centre_row = rows[62 * (1 + 880) : 63 * (1 + 880)]
    centre = centre_row[1 + 110 * 4 : 1 + 111 * 4]
    assert corner == bytes((24, 26, 31, 255))
    assert centre[1] > 150 and centre[2] > 150 and centre[0] < 60


def count_fed_lines(monkeypatch) -> list[int]:
    lines: list[int] = []
    original = ThumbnailScanner.feed

    def counting(self, line):
        lines.append(1)
        return original(self, line)

    monkeypatch.setattr(ThumbnailScanner, "feed", counting)
    return lines


@needs_samples
def test_big_file_is_scanned_up_to_the_first_command(monkeypatch):
    lines = count_fed_lines(monkeypatch)
    assert extract_from_file(SAMPLES / "3dbenchy_prusaslicer.gcode") is not None
    assert len(lines) < 1000  # 3.4 MB file, thumbnail header of ~400 lines


def test_file_without_thumbnail_is_scanned_quickly(monkeypatch, tmp_path):
    gcode = tmp_path / "plain.gcode"
    header = "; generated by PrusaSlicer 2.9.6\n;\n; perimeters extrusion width = 0.45mm\n\n"
    gcode.write_text(header + "G1 X10 Y10 E0.5\n" * 50_000, encoding="utf-8")
    lines = count_fed_lines(monkeypatch)
    assert extract_from_file(gcode) is None
    assert len(lines) < 10


def test_qoi_decoder_handles_every_opcode():
    # 1x5: RGB, index hit, diff, luma, run of 2 (hand-encoded).
    data = (
        b"qoif"
        + struct.pack(">II", 5, 1)
        + bytes([4, 0])
        + bytes([0xFE, 100, 150, 200])  # RGB
        + bytes([0x40 | (3 << 4) | (2 << 2) | 1])  # DIFF +1, 0, -1
        + bytes([0x80 | (32 + 10), (8 + 2) << 4 | (8 - 3)])  # LUMA dg=10, dr-dg=2, db-dg=-3
        + bytes([0xC0 | 1])  # RUN 2
        + b"\x00" * 7
        + b"\x01"
    )
    width, height, rgba = decode_qoi(data)
    assert (width, height) == (5, 1)
    pixels = [tuple(rgba[i : i + 4]) for i in range(0, len(rgba), 4)]
    assert pixels == [
        (100, 150, 200, 255),
        (101, 150, 199, 255),
        (113, 160, 206, 255),
        (113, 160, 206, 255),
        (113, 160, 206, 255),
    ]


def test_scanner_rules(tmp_path):
    jpg = b"\xff\xd8\xff\xe0" + b"fake jpeg"
    gcode = tmp_path / "x.gcode"
    gcode.write_text(
        "; generated by test\n\n"
        + block("thumbnail", 16, 16, tiny_png(16, 16))
        + block("thumbnail_JPG", 64, 48, jpg)
        + block("thumbnail", 99, 99, b"not an image")
        + "G28\n"
        + block("thumbnail", 400, 400, tiny_png(400, 400)),
        encoding="utf-8",
    )
    thumb = extract_from_file(gcode)
    # The block after the first command is ignored; invalid images are skipped.
    assert thumb is not None and thumb.mime == "image/jpeg" and thumb.data == jpg


async def test_endpoint_reads_uploads_and_caches(make_client, tmp_path, monkeypatch):
    uploads = tmp_path / "uploads" / "parts"
    uploads.mkdir(parents=True)
    (uploads / "cube.gcode").write_text(block("thumbnail", 8, 8, tiny_png(8, 8)) + "G28\n")
    (uploads / "plain.gcode").write_text("G28\n")
    client = await make_client()

    resp = await client.get("/local/thumbnail", params={"path": "parts/cube.gcode", "v": "1"})
    assert resp.status == 200
    assert resp.content_type == "image/png"
    assert png_size(await resp.read()) == (8, 8)

    def boom(path):
        raise AssertionError("cache miss")

    monkeypatch.setattr(thumbnails, "extract_from_file", boom)
    assert (await client.get("/local/thumbnail", params={"path": "parts/cube.gcode"})).status == 200

    monkeypatch.undo()
    resp = await client.get("/local/thumbnail", params={"path": "parts/plain.gcode"})
    assert resp.status == 404
    assert (await resp.json())["error"] == "no_thumbnail"
    assert list((tmp_path / "data" / "thumbnails").glob("*.none"))


@pytest.mark.parametrize(
    "path", ["../secret.gcode", "/etc/passwd.gcode", "parts/../../x.gcode", "a.txt", ""]
)
async def test_endpoint_rejects_bad_paths(make_client, path):
    client = await make_client()
    resp = await client.get("/local/thumbnail", params={"path": path})
    assert resp.status == 400


async def test_endpoint_falls_back_to_the_octoprint_download(make_client, upstream):
    upstream.app[STORAGE]["my files/cube #1.gcode"] = (
        block("thumbnail", 12, 10, tiny_png(12, 10)) + "G28\n"
    ).encode()
    client = await make_client(uploads_dir="/nonexistent")
    resp = await client.get("/local/thumbnail", params={"path": "my files/cube #1.gcode"})
    assert resp.status == 200
    assert png_size(await resp.read()) == (12, 10)
    resp = await client.get("/local/thumbnail", params={"path": "missing.gcode"})
    assert resp.status == 404


def test_cache_is_pruned(tmp_path):
    cache = thumbnails.ThumbnailCache(tmp_path / "c", max_entries=3)
    for i in range(5):
        cache._store(f"k{i}", None)
    assert len(list((tmp_path / "c").iterdir())) == 3


def test_png_encoder_roundtrip():
    data = encode_png(2, 1, bytes([1, 2, 3, 4, 5, 6, 7, 8]))
    assert png_size(data) == (2, 1)
    assert png_pixels(data) == b"\x00" + bytes([1, 2, 3, 4, 5, 6, 7, 8])


@needs_samples
async def test_usb_thumbnail(make_client, tmp_path):
    usb = tmp_path / "media" / "usb0"
    usb.mkdir(parents=True)
    shutil.copy(SAMPLES / "tatara-logo_orcaslicer.gcode", usb / "logo.gcode")
    client = await make_client()
    resp = await client.get("/local/usb/thumbnail", params={"mount": "usb0", "path": "logo.gcode"})
    assert resp.status == 200
    assert png_size(await resp.read()) == (300, 300)
