from __future__ import annotations

from floppyoctotouch_agent.objects import ObjectScanner, convex_hull, scan_file


def scan(text: str) -> dict:
    scanner = ObjectScanner()
    for line in text.splitlines():
        scanner.feed(line)
    return scanner.result()


def square(x: float, y: float, size: float = 10, e: str = "E1") -> str:
    """Relative-extrusion perimeter of a square with its lower-left corner at x, y."""
    return "\n".join(
        [
            f"G1 X{x} Y{y} F9000",
            f"G1 X{x + size} Y{y} {e}",
            f"G1 X{x + size} Y{y + size} {e}",
            f"G1 X{x} Y{y + size} {e}",
            f"G1 X{x} Y{y} {e}",
        ]
    )


def by_name(result: dict) -> dict:
    return {o["name"]: o for o in result["objects"]}


def test_convex_hull_drops_inner_points():
    hull = convex_hull([(0, 0), (10, 0), (10, 10), (0, 10), (5, 5), (5, 0)])
    assert sorted(hull) == [(0, 0), (0, 10), (10, 0), (10, 10)]
    assert convex_hull([(1, 1)]) == [(1, 1)]


PRUSA_COMMENTS = f"""; generated by PrusaSlicer 2.8.1
M83

; printing object Cube id:0 copy 0
; stop printing object Cube id:0 copy 0
; printing object Cube id:1 copy 0
; stop printing object Cube id:1 copy 0

G1 Z0.2
; printing object Cube id:0 copy 0
{square(10, 10)}
; stop printing object Cube id:0 copy 0
G1 X200 Y200 E1
; printing object Cube id:1 copy 0
{square(50, 60)}
; stop printing object Cube id:1 copy 0
"""


def test_prusaslicer_comments():
    result = scan(PRUSA_COMMENTS)
    assert result["labels"] == ["comments"]
    assert result["processed"] is False
    assert [o["name"] for o in result["objects"]] == ["Cube id:0 copy 0", "Cube id:1 copy 0"]
    first, second = result["objects"]
    assert first["bbox"] == [10, 10, 20, 20]
    assert first["center"] == [15, 15]
    assert second["bbox"] == [50, 60, 60, 70]
    assert first["m486"] is None
    # The move outside any object (to 200, 200) belongs to nobody.
    assert all(o["bbox"][2] < 200 for o in result["objects"])


def test_prusaslicer_objects_info_outline_wins():
    text = (
        PRUSA_COMMENTS
        + '; objects_info = {"objects":[{"name":"Cube id:0 copy 0","polygon":'
        + "[[8.0,8.0],[22.0,8.0],[22.0,22.0],[8.0,22.0]]}]}\n"
    )
    first = by_name(scan(text))["Cube id:0 copy 0"]
    assert first["bbox"] == [8, 8, 22, 22]
    assert len(first["polygon"]) == 4


def test_plugin_markers_mark_the_file_processed():
    text = PRUSA_COMMENTS.replace("; printing object ", "@Object ").replace(
        "; stop printing object ", "@Objectstop "
    )
    result = scan(text)
    assert result["processed"] is True
    assert result["labels"] == ["plugin"]
    assert by_name(result)["Cube id:1 copy 0"]["bbox"] == [50, 60, 60, 70]


def test_m486_with_names_like_prusaslicer_firmware_labels():
    text = f"""M83
M486 S0
M486 AShape-Box
M486 S-1
M486 S1
M486 AShape Cylinder
M486 S-1
M486 S0
{square(10, 10)}
M486 S-1
M486 S1
{square(100, 100, 20)}
M486 S-1
"""
    result = scan(text)
    assert result["labels"] == ["m486"]
    objects = by_name(result)
    assert set(objects) == {"Shape-Box", "Shape Cylinder"}
    assert objects["Shape-Box"]["m486"] == 0
    assert objects["Shape Cylinder"]["m486"] == 1
    assert objects["Shape Cylinder"]["bbox"] == [100, 100, 120, 120]


def test_m486_without_names():
    text = f"M83\nM486 T2\nM486 S0\n{square(0, 0)}\nM486 S1\n{square(30, 0)}\nM486 S-1\n"
    objects = by_name(scan(text))
    assert set(objects) == {"#0", "#1"}
    assert objects["#1"]["m486"] == 1


def test_absolute_extrusion_and_retractions():
    text = """M82
G92 E0
; printing object A
G1 X0 Y0 F9000
G1 X10 Y0 E1
G1 E0.2
G1 X80 Y80 F9000
G1 X0 Y10
G1 E1
G1 X10 Y10 E2
; stop printing object A
"""
    # The travel to 80,80 happens with the filament retracted: not part of the object.
    assert scan(text)["objects"][0]["bbox"] == [0, 0, 10, 10]


def test_cura_mesh_and_klipper():
    cura = f";MESH:Part.stl\nM83\n{square(5, 5)}\n;MESH:NONMESH\nG1 X100 Y100 E1\n"
    result = scan(cura)
    assert result["labels"] == ["cura"]
    assert result["objects"][0]["bbox"] == [5, 5, 15, 15]

    klipper = (
        "EXCLUDE_OBJECT_DEFINE NAME='part_1' CENTER=15,15"
        " POLYGON=[[10,10],[20,10],[20,20],[10,20]]\n"
        "M83\nEXCLUDE_OBJECT_START NAME='part_1'\n"
        f"{square(12, 12, 2)}\nEXCLUDE_OBJECT_END NAME='part_1'\n"
    )
    result = scan(klipper)
    assert result["labels"] == ["klipper"]
    assert result["objects"][0]["bbox"] == [10, 10, 20, 20]


def test_no_labels():
    result = scan(f"M83\n{square(0, 0)}\n")
    assert result == {"objects": [], "labels": [], "processed": False, "truncated": False}


def test_scan_file(tmp_path):
    path = tmp_path / "part.gcode"
    path.write_text(PRUSA_COMMENTS)
    assert len(scan_file(path)["objects"]) == 2


async def test_objects_endpoint_and_cache(make_client, tmp_path):
    uploads = tmp_path / "uploads" / "parts"
    uploads.mkdir(parents=True)
    (uploads / "two.gcode").write_text(PRUSA_COMMENTS)
    client = await make_client()
    resp = await client.get("/local/objects", params={"path": "parts/two.gcode"})
    assert resp.status == 200
    body = await resp.json()
    assert [o["name"] for o in body["objects"]] == ["Cube id:0 copy 0", "Cube id:1 copy 0"]
    assert list((tmp_path / "data" / "objects").glob("*.json"))
    again = await client.get("/local/objects", params={"path": "parts/two.gcode"})
    assert await again.json() == body

    assert (await client.get("/local/objects", params={"path": "parts/none.gcode"})).status == 404
    assert (await client.get("/local/objects", params={"path": "../etc/passwd"})).status == 400
    assert (await client.get("/local/objects", params={"path": "parts/two.txt"})).status == 400
